import type { ICD11Entry } from './icd11Service';

export type ICFComponent = 'body-functions' | 'body-structures' | 'activities-participation' | 'environmental-factors';

export interface ICFEntry extends ICD11Entry {
  component: ICFComponent;
  qualifierScale?: '0-4' | '0-9';
}

const icfDataset: ICFEntry[] = [
  { code: 'b110', title: 'Consciousness functions', chapter: 'Body Functions', component: 'body-functions', description: 'General mental functions of the state of awareness and alertness, including the clarity and continuity of the wakeful state' },
  { code: 'b114', title: 'Orientation functions', chapter: 'Body Functions', component: 'body-functions', description: 'Mental functions that produce knowledge of one\'s relationship to self, time, place and others' },
  { code: 'b130', title: 'Energy and drive functions', chapter: 'Body Functions', component: 'body-functions', description: 'General mental functions of physiological and psychological energy and drive, including motivation, appetite, and impulse control' },
  { code: 'b134', title: 'Sleep functions', chapter: 'Body Functions', component: 'body-functions', description: 'General mental functions of the periodic, reversible and selective state of disengagement from the environment' },
  { code: 'b140', title: 'Attention functions', chapter: 'Body Functions', component: 'body-functions', description: 'Specific mental functions of focusing on an external stimulus or internal experience for a period of time' },
  { code: 'b144', title: 'Memory functions', chapter: 'Body Functions', component: 'body-functions', description: 'Specific mental functions involved in registering, storing and retrieving information' },
  { code: 'b152', title: 'Emotional functions', chapter: 'Body Functions', component: 'body-functions', description: 'Specific mental functions related to the feeling and affective components of the processes of the mind' },
  { code: 'b164', title: 'Higher-level cognitive functions', chapter: 'Body Functions', component: 'body-functions', description: 'Specific mental functions especially dependent on the frontal lobes, including abstraction, insight, judgment, and problem-solving' },
  { code: 'b176', title: 'Mental function of sequencing complex movements', chapter: 'Body Functions', component: 'body-functions', description: 'Mental functions of ordering and executing complex, coordinated movements' },
  { code: 'b210', title: 'Seeing functions', chapter: 'Body Functions', component: 'body-functions', description: 'Sensory functions relating to sensing the presence of light and the form, size, shape and colour of visual stimuli' },
  { code: 'b230', title: 'Hearing functions', chapter: 'Body Functions', component: 'body-functions', description: 'Sensory functions relating to sensing the presence of sounds and discriminating the location, pitch, loudness and quality of sounds' },
  { code: 'b235', title: 'Vestibular functions', chapter: 'Body Functions', component: 'body-functions', description: 'Sensory functions relating to position, balance and movement of the body' },
  { code: 'b240', title: 'Sensations associated with hearing and vestibular function', chapter: 'Body Functions', component: 'body-functions', description: 'Sensations such as dizziness, falling, tinnitus, and vertigo' },
  { code: 'b250', title: 'Taste function', chapter: 'Body Functions', component: 'body-functions', description: 'Sensory functions relating to sensing the presence and properties of bitter, sweet, sour and salty flavours' },
  { code: 'b255', title: 'Smell function', chapter: 'Body Functions', component: 'body-functions', description: 'Sensory functions relating to sensing the presence and properties of odours' },
  { code: 'b260', title: 'Proprioceptive function', chapter: 'Body Functions', component: 'body-functions', description: 'Sensory functions relating to sensing the relative position of body parts' },
  { code: 'b265', title: 'Touch function', chapter: 'Body Functions', component: 'body-functions', description: 'Sensory functions relating to sensing surfaces and their texture or quality' },
  { code: 'b270', title: 'Sensory functions related to temperature and other stimuli', chapter: 'Body Functions', component: 'body-functions', description: 'Sensory functions relating to sensing temperature, vibration, pressure and noxious stimuli' },
  { code: 'b280', title: 'Sensation of pain', chapter: 'Body Functions', component: 'body-functions', description: 'Sensation of unpleasant feeling indicating potential or actual damage to body structure' },
  { code: 'b310', title: 'Voice functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the production of various sounds by the passage of air through the larynx' },
  { code: 'b320', title: 'Articulation functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the production of speech sounds through coordinated movement of the articulators' },
  { code: 'b330', title: 'Fluency and rhythm of speech functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the production of fluent and rhythmic flow of speech, including stuttering and cluttering' },
  { code: 'b340', title: 'Alternative vocalization functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the production of other vocalizations, including singing and humming' },
  { code: 'b410', title: 'Heart functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of pumping blood in adequate amounts and pressure throughout the body' },
  { code: 'b420', title: 'Blood pressure functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of maintaining the pressure of blood in the arteries' },
  { code: 'b430', title: 'Haematological system functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of blood production, oxygen carriage, and coagulation' },
  { code: 'b435', title: 'Immunological system functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the body\'s defence against foreign substances, including immune responses and allergy' },
  { code: 'b440', title: 'Respiration functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of inhaling air into the lungs, exchanging gases, and exhaling air' },
  { code: 'b450', title: 'Additional respiratory functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of coughing, sneezing, yawning and clearing the respiratory passages' },
  { code: 'b455', title: 'Exercise tolerance functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of respiratory and cardiovascular capacity as required for sustained physical exertion' },
  { code: 'b510', title: 'Ingestion functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions related to taking in and manipulating solids and liquids through the mouth into the body' },
  { code: 'b515', title: 'Digestive functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of transport of food through the gastrointestinal tract, breakdown and absorption of nutrients' },
  { code: 'b525', title: 'Defecation functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of elimination of waste from the rectum, including frequency, consistency and continence' },
  { code: 'b530', title: 'Weight maintenance functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of maintaining appropriate body weight, including weight gain and loss' },
  { code: 'b535', title: 'Sensations associated with the digestive system', chapter: 'Body Functions', component: 'body-functions', description: 'Sensations including nausea, feeling bloated, and abdominal cramps' },
  { code: 'b540', title: 'General metabolic functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of regulating the essential metabolic processes of the body, including temperature and energy metabolism' },
  { code: 'b545', title: 'Water, mineral and electrolyte balance functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of regulating water, minerals and electrolytes in the body, including hydration and electrolyte homeostasis' },
  { code: 'b550', title: 'Thermoregulatory functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of regulating body temperature, including heat production, heat loss and fever' },
  { code: 'b555', title: 'Endocrine gland functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of hormone production and regulation by endocrine glands' },
  { code: 'b560', title: 'Growth maintenance functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of achieving and maintaining appropriate physical growth and development' },
  { code: 'b610', title: 'Urinary excretory functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of filtration and collection of urine by the kidneys' },
  { code: 'b620', title: 'Urination functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of discharge of urine from the urinary bladder, including frequency and continence' },
  { code: 'b630', title: 'Sensations associated with urinary functions', chapter: 'Body Functions', component: 'body-functions', description: 'Sensations including the urge to urinate, pain or discomfort during urination' },
  { code: 'b640', title: 'Sexual functions', chapter: 'Body Functions', component: 'body-functions', description: 'Mental and physical functions related to the sexual act, including arousal, erection and orgasm' },
  { code: 'b650', title: 'Menstruation functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the menstrual cycle, including regularity, duration and volume of menstrual flow' },
  { code: 'b660', title: 'Procreation functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of fertility, pregnancy, and childbirth' },
  { code: 'b670', title: 'Sensations associated with genital and reproductive functions', chapter: 'Body Functions', component: 'body-functions', description: 'Sensations including dyspareunia and other genital discomfort' },
  { code: 'b710', title: 'Mobility of joint functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the range and ease of movement of a joint, including flexion, extension and rotation' },
  { code: 'b715', title: 'Stability of joint functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of maintaining structural integrity of joints, including joint laxity and dislocation' },
  { code: 'b730', title: 'Muscle power functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the force generated by contraction of a muscle or muscle groups' },
  { code: 'b735', title: 'Muscle tone functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the resting tension present in muscles, including spasticity and flaccidity' },
  { code: 'b740', title: 'Muscle endurance functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of sustaining muscle contraction for a required period, including muscle fatigability' },
  { code: 'b750', title: 'Motor reflex functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of involuntary contraction of muscles automatically induced by specific stimuli' },
  { code: 'b755', title: 'Involuntary movement reaction functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of unintentional, non-reflex body movements, including postural and righting reactions' },
  { code: 'b760', title: 'Control of voluntary movement functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of controlling and coordinating voluntary movements, including hand-eye coordination' },
  { code: 'b765', title: 'Involuntary movement functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of unintentional movements, including tremors, tics, and dyskinesia' },
  { code: 'b770', title: 'Gait pattern functions', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of movement patterns associated with walking, running and moving in other ways' },
  { code: 'b810', title: 'Protective functions of the skin', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the skin for protecting the body from physical, chemical and biological threats' },
  { code: 'b820', title: 'Repair functions of the skin', chapter: 'Body Functions', component: 'body-functions', description: 'Functions of the skin for repairing wounds and other damage to the skin, including wound healing' },
  { code: 'b840', title: 'Sensation related to the skin', chapter: 'Body Functions', component: 'body-functions', description: 'Sensations including itching, tingling, burning and numbness of the skin' },
  { code: 's110', title: 'Structure of brain', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the brain, including cerebrum, cerebellum and brainstem' },
  { code: 's120', title: 'Spinal cord and related structures', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the spinal cord, nerve roots, and meninges' },
  { code: 's130', title: 'Structure of meninges', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the membranes surrounding the brain and spinal cord' },
  { code: 's200', title: 'Structure of eyeball', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the globe of the eye, including cornea, lens, retina and optic nerve' },
  { code: 's210', title: 'Structure of orbit of eye', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the bony cavity containing the eyeball and associated tissues' },
  { code: 's220', title: 'Structure of middle ear', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the tympanic cavity, ossicles and eustachian tube' },
  { code: 's230', title: 'Structure of external ear', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the auricle, ear canal and tympanic membrane' },
  { code: 's240', title: 'Structure of internal ear', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the cochlea, semicircular canals and vestibular apparatus' },
  { code: 's300', title: 'Structure of mouth', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the oral cavity, including teeth, gums, tongue and palate' },
  { code: 's310', title: 'Structure of pharynx', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the pharynx and associated muscles and tissues' },
  { code: 's320', title: 'Structure of larynx', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the larynx, including vocal cords and cartilages' },
  { code: 's330', title: 'Structure of trachea', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the trachea and bronchial tree' },
  { code: 's340', title: 'Structure of bronchial tree and lungs', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the bronchi, bronchioles, alveoli and lung parenchyma' },
  { code: 's410', title: 'Structure of cardiovascular system', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the heart, arteries, veins and capillaries' },
  { code: 's420', title: 'Structure of immune system', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the lymphatic system, lymph nodes, spleen and thymus' },
  { code: 's430', title: 'Structure of respiratory system', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the nose, sinuses, pharynx, larynx, trachea and lungs' },
  { code: 's440', title: 'Structure of digestive system', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the oesophagus, stomach, intestines, liver, gallbladder and pancreas' },
  { code: 's450', title: 'Structure of nervous system', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the central and peripheral nervous systems' },
  { code: 's710', title: 'Structure of head and neck region', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the head and neck, including skull, cervical vertebrae and soft tissues' },
  { code: 's720', title: 'Structure of shoulder region', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the shoulder girdle, including scapula, clavicle and humeral head' },
  { code: 's730', title: 'Structure of upper extremity', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the arm, forearm, wrist and hand' },
  { code: 's740', title: 'Structure of pelvic region', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the pelvis and pelvic floor, including sacrum, coccyx and hip bones' },
  { code: 's750', title: 'Structure of lower extremity', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the thigh, leg, ankle and foot' },
  { code: 's760', title: 'Structure of trunk', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the thoracic, abdominal and lumbar regions of the trunk' },
  { code: 's770', title: 'Additional musculoskeletal structures related to movement', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of ligaments, tendons, fascia and other connective tissues' },
  { code: 's810', title: 'Structure of skin', chapter: 'Body Structures', component: 'body-structures', description: 'Anatomical structure of the epidermis, dermis and subcutaneous tissue' },
  { code: 'd110', title: 'Watching', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Intentionally using the sense of vision to experience visual stimuli, such as watching a sporting event' },
  { code: 'd115', title: 'Listening', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Intentionally using the sense of hearing to experience auditory stimuli, such as listening to a lecture' },
  { code: 'd140', title: 'Learning to read', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Developing the competence to read written material with comprehension' },
  { code: 'd150', title: 'Learning to calculate', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Developing the competence to perform mathematical operations' },
  { code: 'd155', title: 'Acquiring skills', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Developing basic and complex competencies in sets of integrated actions or tasks' },
  { code: 'd160', title: 'Focusing attention', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Intentionally focusing on specific stimuli, such as filtering out distracting noises' },
  { code: 'd163', title: 'Thinking', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Formulating and manipulating ideas, concepts and information in the mind' },
  { code: 'd166', title: 'Reading', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Performing activities involved in the comprehension and interpretation of written language' },
  { code: 'd170', title: 'Writing', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Using or producing symbols or language to convey information, including written composition' },
  { code: 'd172', title: 'Calculating', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Performing mathematical operations and computations' },
  { code: 'd175', title: 'Solving problems', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Finding solutions to questions or complex situations by identifying and analysing issues' },
  { code: 'd177', title: 'Making decisions', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Making a choice among options, implementing the choice and evaluating the effects' },
  { code: 'd210', title: 'Undertaking a single task', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Carrying out simple or complex single coordinated actions, such as making a cup of tea' },
  { code: 'd220', title: 'Undertaking multiple tasks', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Managing, completing and coordinating multiple tasks simultaneously or in sequence' },
  { code: 'd230', title: 'Carrying out daily routine', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Managing and completing one\'s own daily routine, including time management and planning' },
  { code: 'd240', title: 'Handling stress and other psychological demands', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Managing and adapting to stressful situations and psychological demands' },
  { code: 'd310', title: 'Communicating with - receiving - spoken messages', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Comprehending literal and implied meanings of messages in spoken language' },
  { code: 'd315', title: 'Communicating with - receiving - nonverbal messages', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Comprehending the meaning of nonverbal messages such as gestures and facial expressions' },
  { code: 'd325', title: 'Communicating with - receiving - written messages', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Comprehending the literal and implied meanings of written messages including Braille' },
  { code: 'd330', title: 'Speaking', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Producing words, phrases and longer passages of spoken language with literal and implied meaning' },
  { code: 'd335', title: 'Producing nonverbal messages', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Using gestures, symbols and drawings to convey meaning' },
  { code: 'd345', title: 'Writing messages', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Producing written language to convey meaning, including the use of assistive technology' },
  { code: 'd350', title: 'Conversation', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Starting, sustaining and ending a dialogue with one or more people through spoken or signed language' },
  { code: 'd360', title: 'Using communication devices and techniques', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Using telephones, computers, assistive communication devices and other communication techniques' },
  { code: 'd410', title: 'Changing basic body position', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Getting into and out of a body position and moving from one location to another, such as standing up from a chair' },
  { code: 'd415', title: 'Maintaining a body position', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Staying in the same body position as required, such as sitting or standing for extended periods' },
  { code: 'd420', title: 'Transferring oneself', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Moving from one surface to another, such as from bed to chair' },
  { code: 'd430', title: 'Lifting and carrying objects', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Raising an object from a lower to a higher level and moving it from one place to another' },
  { code: 'd440', title: 'Fine hand use', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Performing coordinated actions of handling objects with hands and fingers, such as picking up a coin' },
  { code: 'd445', title: 'Hand and arm use', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Performing coordinated actions involving the arm and hand, such as reaching and grasping' },
  { code: 'd450', title: 'Walking', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Moving along a surface on foot, step by step, such as walking short or long distances' },
  { code: 'd455', title: 'Moving around', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Moving from place to place by methods other than walking, such as running, climbing or crawling' },
  { code: 'd465', title: 'Moving around using equipment', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Moving from place to place using assistive devices such as a wheelchair, walker or crutches' },
  { code: 'd470', title: 'Using transportation', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Using various forms of transportation as a passenger, including cars, buses and trains' },
  { code: 'd475', title: 'Driving', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Operating and controlling a vehicle to travel from one place to another' },
  { code: 'd510', title: 'Washing oneself', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Washing and drying the whole body or body parts, including bathing, showering and hand washing' },
  { code: 'd520', title: 'Caring for body parts', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Looking after one\'s skin, teeth, hair, nails and other body parts, including grooming' },
  { code: 'd530', title: 'Toileting', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Managing urination, defecation and menstrual care, including cleaning oneself after elimination' },
  { code: 'd540', title: 'Dressing', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Putting on and taking off clothes and footwear in sequence and as culturally appropriate' },
  { code: 'd550', title: 'Eating', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Performing coordinated tasks of eating served food, bringing it to the mouth and consuming it' },
  { code: 'd560', title: 'Drinking', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Taking in liquids, including managing containers, bringing to mouth and consuming' },
  { code: 'd570', title: 'Looking after one\'s health', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Ensuring physical comfort, health and wellness, including managing diet, medication and rest' },
  { code: 'd620', title: 'Acquisition of goods and services', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Selecting, obtaining and transporting all necessities for daily living, including shopping' },
  { code: 'd630', title: 'Preparing meals', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Planning, combining and cooking ingredients for making meals' },
  { code: 'd640', title: 'Doing housework', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Managing and performing household tasks such as cleaning, washing dishes and laundry' },
  { code: 'd660', title: 'Assisting others', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Providing care and assistance to household members and others, including emotional support' },
  { code: 'd710', title: 'Basic interpersonal interactions', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Interacting with people in a contextually and socially appropriate manner, such as showing respect and tolerance' },
  { code: 'd720', title: 'Complex interpersonal interactions', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Maintaining and managing interactions with others, including regulating emotions and social cues' },
  { code: 'd730', title: 'Relating with strangers', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Engaging in temporary contacts with unfamiliar people for a specific purpose' },
  { code: 'd740', title: 'Formal relationships', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Creating and maintaining relationships in formal settings, such as with employers or professionals' },
  { code: 'd760', title: 'Family relationships', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Creating and maintaining relationships with parents, children, siblings and extended family' },
  { code: 'd770', title: 'Intimate relationships', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Creating and maintaining close romantic or intimate relationships between individuals' },
  { code: 'd820', title: 'School education', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Participating in all school-related activities, including attending classes and completing assignments' },
  { code: 'd825', title: 'Vocational training', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Participating in training programmes for specific employment skills and trades' },
  { code: 'd830', title: 'Higher education', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Participating in post-secondary educational programmes including universities and colleges' },
  { code: 'd845', title: 'Acquiring, keeping and terminating a job', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Seeking, securing, maintaining and leaving employment, including preparation and interviews' },
  { code: 'd850', title: 'Remunerative employment', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Performing paid work as an employee or self-employed person' },
  { code: 'd870', title: 'Economic self-sufficiency', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Managing personal finances and economic resources to meet needs and obligations' },
  { code: 'd910', title: 'Community life', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Participating in community, social and civic activities, including clubs and organizations' },
  { code: 'd920', title: 'Recreation and leisure', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Engaging in play, sports, hobbies, arts and other leisure activities' },
  { code: 'd930', title: 'Religion and spirituality', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Engaging in religious or spiritual activities, practices and ceremonies' },
  { code: 'd940', title: 'Human rights', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Exercising individual and collective rights as recognized by international declarations and law' },
  { code: 'd950', title: 'Political life and citizenship', chapter: 'Activities and Participation', component: 'activities-participation', description: 'Participating in political activities, including voting, advocacy and civic engagement' },
  { code: 'e110', title: 'Products or substances for personal consumption', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Food, drink, medications and other substances ingested by a person for nutrition or therapeutic purposes' },
  { code: 'e115', title: 'Products and technology for personal use in daily living', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Devices and products used for daily activities, including assistive technologies and adaptive equipment' },
  { code: 'e120', title: 'Products and technology for personal mobility and transportation', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Devices for indoor and outdoor mobility, including wheelchairs, walkers, canes and vehicle adaptations' },
  { code: 'e125', title: 'Products and technology for communication', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Devices for communication including hearing aids, visual aids, speech-generating devices and telephones' },
  { code: 'e130', title: 'Products and technology for education', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Products and technologies used for learning, including books, computers and educational software' },
  { code: 'e135', title: 'Products and technology for employment', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Tools, equipment and adaptations used in the workplace, including ergonomic furniture' },
  { code: 'e150', title: 'Design, construction and building products of buildings for public use', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Products and technology of buildings designed for public access, including ramps and accessible entrances' },
  { code: 'e155', title: 'Design, construction and building products of buildings for private use', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Products and technology of residential buildings, including home modifications for accessibility' },
  { code: 'e165', title: 'Assets', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Financial and material resources available to a person, including savings, property and income' },
  { code: 'e210', title: 'Physical geography', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Features of the natural environment including landforms, water bodies and geological characteristics' },
  { code: 'e215', title: 'Population', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Demographic characteristics of communities, including density, age distribution and composition' },
  { code: 'e225', title: 'Climate', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Weather patterns and climatic conditions including temperature, precipitation and humidity' },
  { code: 'e230', title: 'Natural events', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Geophysical and meteorological events including earthquakes, floods and hurricanes' },
  { code: 'e235', title: 'Human-caused events', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Events caused by human activity including conflicts, displacement and industrial accidents' },
  { code: 'e240', title: 'Light', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Natural and artificial lighting conditions affecting daily activities and well-being' },
  { code: 'e250', title: 'Sound', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Noise levels and acoustic environment, including volume, pitch and quality of sounds' },
  { code: 'e260', title: 'Air quality', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Indoor and outdoor atmospheric conditions including pollution levels, allergens and ventilation' },
  { code: 'e310', title: 'Immediate family', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Support and relationships with parents, siblings, spouse and children living in the same household' },
  { code: 'e315', title: 'Extended family', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Support and relationships with relatives beyond the immediate family' },
  { code: 'e320', title: 'Friends', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Support and relationships with close acquaintances and companions' },
  { code: 'e325', title: 'Acquaintances, peers, colleagues and community members', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Support from neighbours, work colleagues, classmates and other community members' },
  { code: 'e330', title: 'People in positions of authority', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Support and relationships with supervisors, managers and other authority figures' },
  { code: 'e340', title: 'Personal care providers and personal assistants', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Support from paid and unpaid caregivers, including home health aides and personal attendants' },
  { code: 'e355', title: 'Health professionals', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Support from doctors, nurses, therapists and other healthcare providers' },
  { code: 'e360', title: 'Other professionals', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Support from teachers, social workers, lawyers and other professionals outside healthcare' },
  { code: 'e410', title: 'Individual attitudes of immediate family members', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Attitudes and beliefs of close family members that influence the person\'s functioning' },
  { code: 'e420', title: 'Individual attitudes of friends', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Attitudes and beliefs of friends that influence the person\'s functioning and participation' },
  { code: 'e425', title: 'Individual attitudes of acquaintances and community members', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Attitudes of neighbours and community members that create barriers or facilitators' },
  { code: 'e450', title: 'Individual attitudes of health professionals', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Attitudes of healthcare providers that affect quality of care and access' },
  { code: 'e460', title: 'Societal attitudes', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Prevailing attitudes, beliefs and stigmas in society that affect people with health conditions' },
  { code: 'e465', title: 'Social norms, practices and ideologies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Cultural norms, customs and belief systems that shape expectations and behaviours' },
  { code: 'e510', title: 'Services, systems and policies for consumer goods', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Services and policies related to the production and distribution of consumer products' },
  { code: 'e525', title: 'Housing services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Services for providing, maintaining and financing housing, including social housing programmes' },
  { code: 'e535', title: 'Communication services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Telecommunication, postal and internet services and the policies governing them' },
  { code: 'e540', title: 'Transportation services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Public and private transportation services including accessible transport options and infrastructure' },
  { code: 'e545', title: 'Civil protection services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Emergency response, disaster preparedness and civil defence services' },
  { code: 'e550', title: 'Legal services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Legal aid, courts, and the justice system including laws protecting the rights of persons with disabilities' },
  { code: 'e555', title: 'Associations and organizational services', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Services provided by non-governmental organizations, disability associations and community groups' },
  { code: 'e560', title: 'Media services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'News, entertainment and information media, including accessible formats and content' },
  { code: 'e565', title: 'Economic services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Banking, insurance and financial services, including accessible financial products' },
  { code: 'e570', title: 'Social security services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Social protection programmes including disability benefits, pensions and welfare assistance' },
  { code: 'e575', title: 'General social support services', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Community support services including case management, counselling and referral services' },
  { code: 'e580', title: 'Health services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Healthcare delivery systems including hospitals, clinics, rehabilitation services and health insurance' },
  { code: 'e585', title: 'Education and training services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Educational institutions and policies including inclusive education and special education services' },
  { code: 'e590', title: 'Labour and employment services, systems and policies', chapter: 'Environmental Factors', component: 'environmental-factors', description: 'Employment services including job training, placement, workplace accommodations and anti-discrimination laws' },
];

export function getAllICFCodes(): ICFEntry[] {
  return icfDataset;
}

export function getICFByCode(code: string): ICFEntry | undefined {
  return icfDataset.find((entry) => entry.code.toLowerCase() === code.toLowerCase());
}

export function searchICF(query: string): ICFEntry[] {
  if (!query.trim()) return [];
  const lower = query.toLowerCase();
  return icfDataset.filter(
    (entry) =>
      entry.code.toLowerCase().includes(lower) ||
      entry.title.toLowerCase().includes(lower) ||
      entry.chapter.toLowerCase().includes(lower) ||
      entry.description.toLowerCase().includes(lower)
  );
}

export function getICFByComponent(component: ICFComponent): ICFEntry[] {
  return icfDataset.filter((entry) => entry.component === component);
}
