/**
 * WorkspaceDocumentEditor — Split-pane editor with live preview, TOC, version history, and export.
 * @license SPDX-License-Identifier: Apache-2.0
 */
import React, { useState, useEffect, useRef } from 'react';
import { KBFile, DocumentVersion } from '../types';
import { parse, generateTOC, sanitizeOutput } from '../utils/markdown';
import { Edit, Download, Clock, Plus, X, Eye, Layout, Copy, Printer, Users } from './icons/lucide-shim';
import type { CollabPresence } from '../services/collaborationService';
import DiffView from './DiffView';

function exportToPDF(fileName: string, html: string, isDownload: boolean): void {
  const finalHtml = html;

  const doc = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>${fileName}</title>
<style>
  @page { margin: 2cm; }
  body { max-width: 800px; margin: 0 auto; padding: 2em; font-family: 'Georgia', 'Times New Roman', serif; color: #000; line-height: 1.7; font-size: 12pt; }
  h1 { font-size: 22pt; border-bottom: 2px solid #333; padding-bottom: 0.3em; margin-top: 1.5em; }
  h2 { font-size: 18pt; border-bottom: 1px solid #ccc; padding-bottom: 0.2em; margin-top: 1.2em; }
  h3 { font-size: 15pt; margin-top: 1em; }
  table { border-collapse: collapse; width: 100%; page-break-inside: avoid; }
  th, td { border: 1px solid #666; padding: 0.4em 0.6em; text-align: left; }
  th { background: #eaeaea; font-weight: bold; }
  pre { background: #f0f0f0; padding: 1em; border: 1px solid #ddd; border-radius: 4px; overflow-x: auto; font-size: 10pt; page-break-inside: avoid; }
  code { background: #f0f0f0; padding: 0.15em 0.4em; border-radius: 3px; font-size: 0.9em; }
  img { max-width: 100%; }
  blockquote { border-left: 4px solid #aaa; margin: 1em 0; padding: 0.5em 1em; color: #444; }
  ul, ol { margin: 0.5em 0; padding-left: 2em; }
  li { margin: 0.2em 0; }
  .mermaid { text-align: center; page-break-inside: avoid; }
  .footer { text-align: center; font-size: 10pt; color: #888; margin-top: 3em; border-top: 1px solid #ddd; padding-top: 1em; }
  @media print { body { padding: 0; margin: 0; } .no-print { display: none; } }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.18.1/dist/katex.min.css">
</head><body>
  <div class="no-print" style="text-align:center;margin-bottom:1em;">
    <button onclick="window.print()" style="padding:0.5em 1.5em;font-size:14px;cursor:pointer;background:#333;color:#fff;border:none;border-radius:4px;">
      🖨️ Save as PDF
    </button>
  </div>
  ${finalHtml}
  <div class="footer">Generated by Open Knowledge Studio</div>
  <script src="https://cdn.jsdelivr.net/npm/katex@0.18.1/dist/katex.min.js"><\/script>
  <script>
    document.querySelectorAll('.katex-math, .katex-inline').forEach(function(el) {
      try { katex.render(el.getAttribute('data-math') || '', el, { displayMode: el.classList.contains('katex-math'), throwOnError: false }); }
      catch(e) {}
    });
  <\/script>
</body></html>`;

  if (isDownload) {
    const blob = new Blob([doc], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName.replace(/\.md$/, '') + '.html';
    a.click();
    URL.revokeObjectURL(url);
    return;
  }

  const printWindow = window.open('', '_blank');
  if (!printWindow) return;
  printWindow.document.write(doc);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 800);
}

interface Props {
  file: KBFile | null;
  onSave: (file: KBFile) => void;
  versions: DocumentVersion[];
  onSaveVersion: (docId: string, content: string, label?: string) => void;
  templates: { id: string; name: string; content: string; category: string }[];
  collabPeers?: CollabPresence[];
}

export const WorkspaceDocumentEditor: React.FC<Props> = ({ file, onSave, versions, onSaveVersion, templates, collabPeers }) => {
  const [content, setContent] = useState('');
  const [showTOC, setShowTOC] = useState(true);
  const [showVersions, setShowVersions] = useState(false);
  const [showTemplates, setShowTemplates] = useState(false);
  const [renderedHTML, setRenderedHTML] = useState('');
  const [toast, setToast] = useState('');
  const [diffVersion, setDiffVersion] = useState<DocumentVersion | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const previewRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (file) {
      setContent(file.content);
      const html = parse(file.content);
      setRenderedHTML(html);
    } else {
      setContent('');
      setRenderedHTML('');
    }
  }, [file?.id]);

  // Render KaTeX after content changes
  useEffect(() => {
    const timer = setTimeout(() => {
      if (previewRef.current && (window as any).renderMathInElement) {
        try {
          (window as any).renderMathInElement(previewRef.current, {
            delimiters: [
              { left: '$$', right: '$$', display: true },
              { left: '$', right: '$', display: false },
            ],
            throwOnError: false,
          });
        } catch {}
      }
      // Also render Mermaid
      if (previewRef.current && (window as any).mermaid) {
        const isDark = document.documentElement.classList.contains('dark');
        try { (window as any).mermaid.initialize?.({ theme: isDark ? 'dark' : 'default', startOnLoad: false }); } catch {}
        (window as any).mermaid.run({ nodes: previewRef.current.querySelectorAll('.language-mermaid') });
      }
    }, 100);
    return () => clearTimeout(timer);
  }, [renderedHTML]);

  // Auto-save (debounced)
  useEffect(() => {
    if (!file) return;
    const timer = setTimeout(() => {
      const updated: KBFile = { ...file, content, size: `${(content.length / 1024).toFixed(1)} KB` };
      onSave(updated);
    }, 2000);
    return () => clearTimeout(timer);
  }, [content]);

  const handleContentChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newContent = e.target.value;
    setContent(newContent);
    setRenderedHTML(parse(newContent));
  };

  const handleTOCLinkClick = (id: string) => {
    const el = previewRef.current?.querySelector(`#${id}`);
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  const saveVersion = () => {
    if (!file) return;
    const label = `v${versions.length + 1}`;
    onSaveVersion(file.id, content, label);
    setToast('Version saved');
    setTimeout(() => setToast(''), 2000);
  };

  const exportMarkdown = () => {
    if (!file) return;
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = file.name;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportHTML = () => {
    if (!file) return;
    const htmlDoc = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${file.name}</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.17.0/dist/katex.min.css"></head><body style="max-width:800px;margin:0 auto;padding:2em;font-family:system-ui;"><div class="prose">${renderedHTML}</div></body></html>`;
    const blob = new Blob([htmlDoc], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = file.name.replace(/\.md$/, '.html');
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyContent = () => {
    navigator.clipboard.writeText(content).then(() => {
      setToast('Copied to clipboard');
      setTimeout(() => setToast(''), 2000);
    });
  };

  const injectTemplate = (templateContent: string) => {
    setContent((prev) => prev + '\n\n' + templateContent);
    setShowTemplates(false);
  };

  if (!file) {
    return (
      <div className="flex items-center justify-center h-full text-[var(--text-muted)]">
        <div className="text-center">
          <Edit size={32} className="mx-auto mb-3 opacity-30" />
          <p className="text-sm">Select a file to edit</p>
        </div>
      </div>
    );
  }

  const toc = generateTOC(content);

  return (
    <div className="flex flex-col h-full">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-[var(--border)]">
        <div className="flex items-center gap-2">
          <Edit size={14} className="text-[var(--accent)]" />
          <span className="text-sm font-medium">{file.name}</span>
        </div>
        <div className="flex items-center gap-2">
          {collabPeers && collabPeers.filter((p) => p.activeFileId === file.id).length > 0 && (
            <div className="flex items-center gap-1 text-[10px] text-[var(--text-muted)]" title="Collaborators editing this file">
              <Users size={12} className="text-green-400" />
              <span>{collabPeers.filter((p) => p.activeFileId === file.id).length}</span>
            </div>
          )}
        </div>
        <div className="flex items-center gap-1">
          <button onClick={() => setShowTOC(!showTOC)} className={`p-1.5 rounded ${showTOC ? 'bg-[var(--accent-subtle)] text-[var(--accent)]' : 'hover:bg-[var(--bg-hover)] text-[var(--text-secondary)]'}`} title="Table of Contents" aria-label="Toggle table of contents" aria-expanded={showTOC} aria-controls="toc-panel"><Layout size={14} /></button>
          <button onClick={() => setShowTemplates(!showTemplates)} className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-secondary)]" title="Templates" aria-label="Toggle templates" aria-expanded={showTemplates} aria-controls="templates-panel"><Plus size={14} /></button>
          <button onClick={() => setShowVersions(!showVersions)} className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-secondary)]" title="Versions" aria-label="Toggle version history" aria-expanded={showVersions} aria-controls="versions-panel"><Clock size={14} /></button>
          <button onClick={saveVersion} className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-secondary)]" title="Save version" aria-label="Save version"><Eye size={14} /></button>
          <button onClick={copyContent} className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-secondary)]" title="Copy" aria-label="Copy content"><Copy size={14} /></button>
          <button onClick={exportMarkdown} className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-secondary)]" title="Export .md" aria-label="Export markdown"><Download size={14} /></button>
          <button onClick={exportHTML} className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-secondary)]" title="Export .html" aria-label="Export HTML"><Download size={14} /></button>
          <button onClick={() => exportToPDF(file.name, renderedHTML, false)} className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-secondary)]" title="Print to PDF" aria-label="Print to PDF"><Printer size={14} /></button>
          <button onClick={() => exportToPDF(file.name, renderedHTML, true)} className="p-1.5 rounded hover:bg-[var(--bg-hover)] text-[var(--text-secondary)]" title="Export PDF" aria-label="Download PDF"><Download size={14} /></button>
        </div>
      </div>

      {/* Toast */}
      {toast && (
        <div className="absolute top-12 right-4 z-50 bg-green-600 text-white text-xs px-3 py-1.5 rounded-lg shadow-lg">{toast}</div>
      )}

      {/* Templates panel */}
      {showTemplates && (
        <div id="templates-panel" className="absolute top-12 right-4 z-40 bg-[var(--bg-secondary)] border border-[var(--border)] rounded-lg shadow-xl p-3 w-72 max-h-96 overflow-y-auto">
          <div className="flex justify-between items-center mb-2">
            <span className="text-xs font-medium">Templates</span>
            <button onClick={() => setShowTemplates(false)}><X size={12} /></button>
          </div>
          {templates.map((t) => (
            <button key={t.id} onClick={() => injectTemplate(t.content)} className="block w-full text-left p-2 rounded hover:bg-[var(--bg-hover)] text-xs mb-1">
              <span className="font-medium">{t.name}</span>
              <span className="block text-[10px] text-[var(--text-muted)]">{t.category}</span>
            </button>
          ))}
          {templates.length === 0 && <p className="text-[10px] text-[var(--text-muted)]">No templates available</p>}
        </div>
      )}

      {/* Versions panel */}
      {showVersions && !diffVersion && (
        <div id="versions-panel" className="absolute top-12 right-4 z-40 bg-[var(--bg-secondary)] border border-[var(--border)] rounded-lg shadow-xl p-3 w-80 max-h-96 overflow-y-auto">
          <div className="flex justify-between items-center mb-2">
            <span className="text-xs font-medium">Version History</span>
            <button onClick={() => setShowVersions(false)}><X size={12} /></button>
          </div>
          {versions.filter((v) => v.documentId === file.id).map((v) => (
            <div key={v.id} className="flex items-center gap-2 p-2 rounded hover:bg-[var(--bg-hover)] text-xs">
              <Clock size={12} className="text-[var(--text-muted)] shrink-0" />
              <div className="flex-1 min-w-0">
                <span className="font-medium block truncate">{v.label || 'Version'}</span>
                <span className="block text-[10px] text-[var(--text-muted)] truncate">{new Date(v.createdAt).toLocaleString()} — {v.size}</span>
              </div>
              <div className="flex gap-1 shrink-0">
                <button onClick={() => setDiffVersion(v)} className="text-[10px] px-1.5 py-0.5 rounded bg-[var(--accent-subtle)] text-[var(--accent)] hover:opacity-80">Diff</button>
                <button onClick={() => { setContent(v.content); setRenderedHTML(parse(v.content)); }} className="text-[10px] px-1.5 py-0.5 rounded bg-green-500/10 text-green-400 hover:opacity-80">Restore</button>
              </div>
            </div>
          ))}
          {versions.filter((v) => v.documentId === file.id).length === 0 && <p className="text-[10px] text-[var(--text-muted)]">No versions yet</p>}
        </div>
      )}

      {/* Diff view overlay */}
      {diffVersion && (
        <div className="absolute inset-0 z-50 bg-[var(--bg-primary)]">
          <DiffView
            oldText={diffVersion.content}
            newText={content}
            oldLabel={diffVersion.label || 'v' + (versions.indexOf(diffVersion) + 1).toString()}
            newLabel="Current"
            onClose={() => setDiffVersion(null)}
          />
        </div>
      )}

      {/* Split Pane — editor (left half) | preview (right half) */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left half: TOC sidebar + Editor (TOC doesn't shift the center split) */}
        <div className="flex-1 min-w-0 flex overflow-hidden">
          {showTOC && toc.length > 0 && (
            <div id="toc-panel" className="w-48 border-r border-[var(--border)] overflow-y-auto p-2 shrink-0" role="region" aria-label="Table of contents">
              <div className="text-[10px] text-[var(--text-muted)] uppercase tracking-wider mb-2">Contents</div>
              {toc.map((item) => (
                <button
                  key={item.id}
                  onClick={() => handleTOCLinkClick(item.id)}
                  className="block w-full text-left text-xs py-0.5 hover:text-[var(--accent)] truncate"
                  style={{ paddingLeft: `${(item.level - 1) * 12}px` }}
                >
                  {item.text}
                </button>
              ))}
            </div>
          )}
          <textarea
            ref={textareaRef}
            value={content}
            onChange={handleContentChange}
            className="flex-1 h-full bg-[var(--bg-primary)] text-[var(--text-primary)] px-5 py-4 font-mono text-sm resize-none focus:outline-none leading-relaxed"
            placeholder="Start writing in Markdown..."
            spellCheck={false}
            aria-label="Document editor"
          />
        </div>

        {/* Right half: Preview */}
        <div className="flex-1 min-w-0 border-l border-[var(--border)] overflow-y-auto" aria-label="Preview" role="region">
          <div ref={previewRef} className="prose px-5 py-4" dangerouslySetInnerHTML={{ __html: sanitizeOutput(renderedHTML) }} />
        </div>
      </div>
    </div>
  );
};
