name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  add-reviewers:
    name: Assign reviewers
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: kentaro-m/auto-assign-action@v2.0.2
        with:
          configuration-path: .github/auto-assign.yml

  add-labels:
    name: Label by changed files
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/labeler@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
